[package]
name = "NftProtocol"
version = "0.26.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.27.1
rev = "devnet"

[dependencies.Originmate]
git = "https://github.com/ellen3njoy/originmate.git"
# devnet-0.27.1
rev = "main"

[addresses]
nft_protocol = "0xe38fe4c7e2aece823e13b33c9356f2e92e0209dd"
